openapi: 3.0.3
info:
  title: Base Lamenu documentation
  description: Base Lamenu documentation
  version: 1.0.0
servers:
  - url: 'http://0.0.0.0:8181/api/v1/'
  - url: 'http://188.166.167.80:8181/api/v1/'
    
paths:
  
