openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
paths:
  /staffs:
    get:
      tags:
        - Staff
      description: "Returns a list of all staffs"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/StaffDto'
        "204":
          description: "No content"
  /staff:
    post:
      tags:
        - Staff
      description: "Creates a new staff"
      requestBody:
        description: "A JSON object containing staff information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StaffDto"
      responses:
        "200":
          description: "OK"
    put:
      tags:
        - Staff
      description: "Updates an existing staff"
      requestBody:
        description: "A JSON object containing updated staff information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StaffDto"
      responses:
        "200":
          description: "OK"

  /staff/{id}:
    get:
      tags:
        - Staff
      description: "Returns a staff by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StaffDto"
        "204":
          description: "No content"
        "400":
          description: "Bad request"
    delete:
      tags:
        - Staff
      description: "Deletes a staff by its ID"
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad request"


components:
  schemas:
    StaffDto:
      type: object
      properties:
        id:
          type: "integer"
          format: "long"
        username:
          type: "string"
        password:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        birthDay:
          type: "string"
          format: "yyyy-MM-dd"
        image:
          type: "string"
        position:
          $ref: "#/components/schemas/PositionDto"

    PositionDto:
      type: object
      properties:
        id:
          type: "integer"
          format: "long"
        name:
          type: "string"
        roles:
          type: array
          items:
            $ref: "#/components/schemas/RoleDto"

    RoleDto:
      type: object
      properties:
        id:
          type: "integer"
          format: "long"
        name:
          type: "string"
        staffId:
          type: "integer"
          format: "long"
        menu:
          type: boolean
        delivery:
          type: boolean
