openapi: 3.0.3
info:
  title: Courier documentation
  description: Courier documentation
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:9000/v1/'
    description: 'Local server'
  - url: 'http://188.166.167.80:9000/v1/'
    description: "Host server"
  - url: 'https://api.lamenu.uz/v1/'
    description: "Domain server"
tags:
  - name: Profile
    description: information about profile


paths:
  /courier:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Profile Info
      description: "Get profile info"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                items:
                  $ref: '#/components/schemas/CourierDto'
  /courier/orders/open:
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - Get open orders in merchant
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                items:
                  $ref: '#/components/schemas/OrderDto'
#//==================================================================================================SCHEMAS
components:
  schemas:
    CourierDto:
      type: object
      properties:
        id:
          type: integer
          format: "long"
        firstName:
          type: string
        lastName:
          type: string
        birthDay:
          type: string
          format: "yyyy-MM-dd"
        image:
          type: string
        gender:
          type: string
        status:
          type: boolean
        balance:
          type: integer
          format: "double"


    OrderDto:
        type: "object"
        properties:
          id:
            type: integer
            format: "long"
          branch:
            $ref: '#/components/schemas/BranchDto'
          productCount:
            type: integer
          totalPrice:
            type: integer
            format: "double"
          created:
            type: "string"
            format: "yyyy-MM-dd hh:mm:ss.SSSSSS"
          latitude:
            type: integer
            format: "double"
          longitude:
            type: integer
            format: "double"
          addressName:
            type: string
          deliveryAt:
            type: "string"
            format: "yyyy-MM-dd hh:mm:ss.SSSSSS"
          deliveredAt:
            type: "string"
            format: "yyyy-MM-dd hh:mm:ss.SSSSSS"

    BranchDto:
        type: object
        properties:
          id:
            type: integer
          name:
            $ref: '#/components/schemas/TextModel'

    TextModel:
        type: "object"
        properties:
          uz:
            type: "string"
          ru:
            type: "string"
          eng:
            type: "string"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT