openapi: 3.0.3
info:
  title: Order
  description: Order
  version: 1.0.0
servers:
  - url: 'http://0.0.0.0:8181/api/v1/'
  - url: 'http://188.166.167.80:8181/api/v1/'
paths:
  /staff/orders:
    get:
      tags:
        - Order
      summary: Retrieve orders
      description: Retrieve a list of orders based on status, type, limit, and offset.
      parameters:
        - name: "status"
          in: "query"
          description: "Filter orders by status."
          required: false
          schema:
            type: "string"
        - name: "type"
          in: "query"
          description: "Filter orders by type."
          required: false
          schema:
            type: "string"
        - name: "limit"
          in: "query"
          description: "Maximum number of orders to retrieve."
          required: false
          schema:
            type: "integer"
        - name: "offset"
          in: "query"
          description: "Number of orders to skip before starting to return results."
          required: false
          schema:
            type: "integer"
      responses:
        '200':
          description: "List of orders."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderDto'
        '204':
          description: No orders found.

  /staff/orders/{id}:
    get:
      tags:
         - Order
      description: "Returns a order by its ID"
      parameters:
        - name: id
          in: path
          description: "ID of order to return"
          required: true
          schema:
            type: integer
            format: long
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OrderDto"
        "204":
          description: "No content"
    delete:
      tags:
          - Order
      description: "Deletes a order"
      parameters:
        - name: id
          in: path
          description: "ID of order to delete"
          required: true
          schema:
              type: integer
              format: long
      responses:
          "200":
              description: "OK"


  /staff/order:
    post:
        tags:
            - Order
        description: "Creates a new order"
        requestBody:
            description: "A JSON object containing order information"
            required: true
            content:
              application/json:
                schema:
                  $ref: "#/components/schemas/OrderDto"
        responses:
            "200":
              description: "OK"
    put:
      tags:
        - Order
      description: "Updates an existing order"
      requestBody:
        description: "A JSON object containing updated order information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderDto"
      responses:
        "200":
          description: "OK"

  /staff/live:
    get:
      tags:
        - Order
      summary: Retrieve live orders
      description: Retrieve a list of live orders based on type.
      parameters:
        - name: "type"
          in: "query"
          description: "Filter live orders by type"
          required: false
          schema:
            type: "string"
      responses:
        '200':
          description: "List of live orders."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderDto'
        '204':
          description: No live orders found.
  /staff/history:
    get:
      tags:
        - Order
      summary: Retrieve order history
      description: Retrieve a list of orders from the history
      responses:
        '200':
          description: "List of orders from the history."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/OrderDto'
        '204':
          description: No orders found in history.

components:
  schemas:
    OrderDto:
      type: object
      properties:
        id:
          type: integer
          format: long
        type:
          $ref: "#/components/schemas/OrderType"
        status:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
            type: string
            format: date-time
        deletedAt:
            type: string
            format: date-time
        totalPrice:
          type: integer
        totalDiscount:
          type: integer
        comment:
          type: string


    OrderType:
      type: object
      properties:
        id:
          type: integer
          format: long
        name:
          type: string

    CartItem:
      type: object
      properties:
        product:
          $ref: "./components.yaml#/components/schemas/ProductDto"
        count:
          type: integer
          format: int32

    OrderWrapper:
      type: object
      properties:
        order:
          $ref: "#/components/schemas/OrderDto"
        products:
          type: array
          items:
            $ref: "#/components/schemas/CartItem"
        address:
          $ref: "./components.yaml#/components/schemas/AddressDto"
