openapi: "3.0.3"
info:
  title: "Lamenu documentation Client"
  description: "Lamenu documentation Clint allows to you view the schema of Client Lamenu project"
  version: "1.0.0"
servers:
  - url: 'http://127.0.0.1:9000/v1/'
    description: 'Local server'
  - url: 'http://188.166.167.80:9000/v1/'
    description: "Host server"
  - url: 'https://api.lamenu.uz/v1/'
    description: "Domain server"


tags:
  - name: Device
    description: Endpoints related to device

  - name: Auth
    description: Endpoints related to client authentication

  - name: Menus
    description: Endpoints related to menu

  - name: Profile
    description: Endpoints related to profile

paths:

  /client/device:
    get:
      tags:
        - Device
      description: "Get all client device"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DeviceModel"
        "204":
          description: "No Content"

    post:
      tags:
        - Auth
      description: "Auth client for device"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DeviceModel"
        "204":
          description: "No Content"

  /client/device/terminate:
    post:
      tags:
        - Device
      description: "Terminate device by id"
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "id"
          in: "query"
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        "200":
          description: "OK"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"

  /client/device/terminate/others:
    post:
      tags:
        - Device
      description: "Terminate other devices"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"

  /client/auth/send-sms:
    post:
      tags:
        - Auth
      description: "Auth client sms"
      security:
        - bearerAuth: [ ]
      requestBody:
        description: "A JSON object receive client's phone"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone:
                  type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DeviceModel"
        "204":
          description: "No Content"

  /client/auth/verify:
    post:
      tags:
        - Auth
      description: "Auth client verify"
      security:
        - bearerAuth: [ ]
      requestBody:
        description: "A JSON object receive sms code"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                code:
                  type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DeviceModel"
        "204":
          description: "No Content"

  /client/auth/sign-up:
    post:
      tags:
        - Auth
      description: "Auth client sign up"
      security:
        - bearerAuth: [ ]
      requestBody:
        description: "A JSON object receive with sign up"
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: "string"
                lastName:
                  type: "string"
                image:
                  type: "string"
                birthDay:
                  type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/DeviceModel"
        "204":
          description: "No Content"

  /client/menus:
    get:
      tags:
        - Menus
      description: "Returns a list of all menus"
      security:
        - bearerAuth: [ ]

      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MenuDto"
        "204":
          description: "No Content"

  /client/profile:
    get:
      tags:
        - Profile
      description: "Returns profile by its ID"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"
    put:
      tags:
        - Profile
      description: "Update client profile"
      security:
        - bearerAuth: [ ]
      requestBody:
        description: "A JSON object containing updated profile's information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserDto"
      responses:
        "200":
          description: "OK"

  /client/profile/logout:
    post:
      tags:
        - Profile
      description: "Profile logout"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"

  /client/profile/delete:
    post:
      tags:
        - Profile
      description: "Profile delete"
      security:
        - bearerAuth: [ ]
      responses:
        "200":
          description: "OK"
        "204":
          description: "No Content"
        "400":
          description: "Bad Request"

  /client/profile/firebase:
    put:
      tags:
        - Profile
      description: "Update client profile firebase"
      security:
        - bearerAuth: [ ]
      requestBody:
        description: "A JSON object containing updated profile's information"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceModel"
      responses:
        "200":
          description: "OK"












#//==================================================================================================SCHEMAS
components:
  schemas:


    MenuDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "long"
        name:
          $ref: "#/components/schemas/TextModel"

    UserDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "long"
        merchantId:
          type: "integer"
          format: "long"
        badge:
          $ref: '#/components/schemas/BadgeDto'
        phone:
          type: "string"
        firstName:
          type: "string"
        lastName:
          type: "string"
        image:
          type: "string"
        birthDay:
          type: "string"
        token:
          type: "string"

    BadgeDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "long"
        merchantId:
          type: "integer"
          format: "long"
        name:
          $ref: '#/components/schemas/TextModel'
        textColor:
          type: "string"
        bgColor:
          type: string
        icon:
          type: string

    TextModel:
      type: "object"
      properties:
        uz:
          type: "string"
        ru:
          type: "string"
        eng:
          type: "string"

    DeviceModel:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "long"
        uuid:
          type: "string"
        osVersion:
          type: "string"
        model:
          type: "string"
        brand:
          type: "string"
        build:
          type: "string"
        firebaseToken:
          type: "string"
        ip:
          type: "string"
        token:
          type: "string"
        blockedUntil:
          type: "string"
          format: "date-time"
        code:
          type: "string"
        action:
          type: "string"
        expAction:
          type: "boolean"
        phone:
          type: "string"



  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
