openapi: "3.0.3"
info:
  title: "Lamenu documentation Client"
  description: "Lamenu documentation Clint allows to you view the schema of Client Lamenu project"
  version: "1.0.0"
servers:
  - url: 'http://127.0.0.1:9000/v1/'
  - url: 'http://188.166.167.80:9000/v1/'

tags:


  - name: Menus
    description: Endpoints related to menu
paths:

  /client/menus:
    get:
      tags:
        - Menus
      description: "Returns a list of all menus"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/MenuDto"
        "204":
          description: "No Content"

#//==================================================================================================SCHEMAS
components:
  schemas:
    MenuDto:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "long"
        name:
          $ref: "#/components/schemas/TextModel"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
